### ISSUE TITLE
YAML SafeLoader converts multi-day time deltas to integers

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/uwtools#314]
**Expected behavior**

When loading a YAML config file with a multi day time stamp:

```
time: 48:00:00
number: 123
```

The resulting in-memory dict, should reflect the input YAML with the result:

```
{'time': '48:00:00', 'number':  123}
```

**Current behavior**

The multi-day time stamp is converted to an integer using the YAML safe loader, so the in-memory dict becomes:

```
{'time': 172800, 'number': 123}
```

**To Reproduce**

In the Python interpreter

```
>>> yaml_str = """
... time: 48:00:00
... number: 123
... """
>>> 
>>> 
>>> yaml.safe_load(yaml_str)
{'time': 172800, 'number': 123}
```

**Context**

MPAS needs time stamps like these to indicate the duration of the forecast. When running user YAML configs through the realization process, the values get converted to integers and are not in the appropriate format expected by MPAS.

**Possible Implementation**

Updating the behavior of the `yaml.SafeLoader` base class to exclude this conversion or building a constructor for this type of entry.

**Comment by maddenp-noaa** [comment]
This can be resolved when we remove the `_reify_scalar_str()` method, which gets called via `dereference()`. The solution will be to quote this value in the YAML so that `libyaml` doesn't parse it as an integer. That would work now except that `_reify_scalar_str()` does a second parse of the value -- initially parsed as hoped to a string -- and turns it into an integer. Removal of `_reify_scalar_str()` depends on us working [UW-419](https://jira.epic.oarcloud.noaa.gov/browse/UW-419) to disable translations between incompatible formats so that we won't need to try to convert values to other types.

**Comment by maddenp-noaa** [comment]
This was addressed by [UW-419](https://jira.epic.oarcloud.noaa.gov/browse/UW-419). It does require quoting, i.e. `"48:00:00`" in YAML, but `uwtools` will no longer subsequently re-parse that string to an integer. Closing...
