### ISSUE TITLE
uw config realize does not report error if it can not parse update values given via stdin

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/uwtools#599]
**Expected behavior**
When passing update values through stdin, if those values are invalid or can not be parsed, uw config should acknowledge this with an error message

**Current behavior**
Invalid input via stdin is ignored, and the tool reports success.

**Machines affected**
All

**To Reproduce**
An MRE in a bash shell for your enjoyment:
```
$ cat << EOF > template.namelist
 &fire
   fire_num_ignitions = 1
 /
EOF
$ settings="&fire
   fire_num_ignitions = 2
/
"

```
So if I use the correct command, I should expect that in the output, `fire_num_ignitions` will be updated to 2 from the initial value 1. And I do indeed see this:

```
$ echo $settings | uw config realize --update-format nml --input-format nml --output-format nml --input-file template.namelist 
&fire
    fire_num_ignitions = 2
/
```

However, if the update values passed through stdin are invalid or the wrong format (which can happen if, in this example, you forget the `--update-format nml` flag and so the tool defaults to interpreting it as yaml input), the tool simply returns the input namelist:

```
$ echo $settings | uw config realize --input-format nml --output-format nml --input-file template.namelist 
&fire
    fire_num_ignitions = 1
/
```

**Possible Implementation**
Not sure if this should be a warning or a fatal error (I would argue the latter), but there should be at least *some* indication that the tool received invalid input.

**Comment by christinaholtNOAA** [comment]
@mkavulich I was just trying to understand the use case a little better and re-running some things on my own. In my exploration, I used your same input file and `settings` variable, but changed the `--update-format` to `yaml` and found that we do get an ERROR. I'm not sure the error is particularly helpful. Perhaps a bit more feedback that the format was incorrect wrong would be better.

```
$ echo $settings | uw config realize --update-format yaml --input-format nml --output-format nml --input-file template.namelist 
[2024-08-30T12:21:17]    ERROR Parsed a str value from stdin, expected a dict
```

If there is a problem with the format of the `$settings` variable, you get a better error. Here, I redefined `settings` to remove the closing backslash, and re-ran:

```
$ echo $settings | uw config realize --update-format nml --input-format nml --output-format yaml --input-file template.namelist 

...long stack trace...

  File "/Users/christina.holt/conda/envs/DEV-uwtools/lib/python3.12/site-packages/f90nml/parser.py", line 283, in read
    raise ValueError('End-of-file reached before end of namelist.')
ValueError: End-of-file reached before end of namelist.
```

Your expectations of the behavior above (no change in the output when the `--udpate-format` argument was not included) may have been a bit misguided. The existence of the `--update-format` flag is what will tell the tool to read from STDIN. There was no error in this case because it wasn't instructed to read STDIN. It does not default to reading from STDIN if the flag is not provided.

**Comment by maddenp-noaa** [comment]
This is [documented behavior](https://uwtools.readthedocs.io/en/stable/sections/user_guide/cli/tools/config.html):

> Only if either `--update-file` or `--update-config` are specified will `uw` attempt to read and apply update values to the input config.

All Unix tools will accept, but silently ignore, input on `stdin` if they're not told to use it, or do not use it as a fallback, e.g.
```
$ echo "ignore me" | grep maddenp /etc/passwd
maddenp:x:1000:1000:maddenp:/home/maddenp:/bin/bash
```

Maybe we could add something to the `uw config realize --help` output to clarify this but, then again, comprehensive documentation is seldom available via `--help` when e.g. web-based docs are available for reference. Is there something concise we could say via `--help` that would have helped here?

@christinaholtNOAA in re:
> Perhaps a bit more feedback that the format was incorrect wrong would be better.

The format was not incorrect, though. You told `uw` to expect YAML, and it got YAML: Any string is valid YAML.
```
>>> yaml.safe_load("a string")
'a string'
```
But `uw` only accepts `dict`-based YAML as configs, and said so.

**Comment by christinaholtNOAA** [comment]
I don't think I have anything to add.

**Comment by maddenp-noaa** [comment]
Thanks. Hopefully the discussion that happened here will be useful to others if they search Issues looking for solutions.
