### ISSUE TITLE
Output method for UPP driver

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/uwtools#627]
# AC

- [ ] Implementing the output method.
- [ ] Provide the output files in an appropriate data structure (dict) as a public helper method on the object.
- [ ] Update unit tests
- [ ] Add doc block to the method that shows what the output looks like (data structure with example values filled in)
- [ ] Add something to the CLI that prints out this information in a pretty-printed format (YAML). Can use it to generate docs.

# Description

Use the config from the UPP to understand the naming convention of the output.
Can have an "unknown" option.
Returns a dictionary.
Documentation of the configured output shows up in the CLI docs. 
Doc block that shows up in API shows an unconfigured example.

**Comment by maddenp-noaa** [comment]
Here's what we've discovered:

- The prefix for GRIB output filenames is encoded in the `<datset>` tag in the XML from which the `postxconfig-NT.txt` control file read by UPP is derived. Unfortunately, in SRW, the source XML file is not necessarily available at run time.
- But the prefix can be extracted from `postxconfig-NT.txt`, albeit via a somewhat byzantine method that involves reading blocks of lines and finding the required string in a specific place.
- Unfortunately, SRW and MPAS App currently use different UPP versions for which the method alluded to above must differ, given that the blocks of lines are of different sizes.
- The suffix for GRIB output filenames appears to be decided in Fortran code based on a [difficult-to-decipher recipe](https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/get_postfilename.f), but for the applications we're currently interested in, appears to be `.GrbF*`, where the `*` is the zero-padded forecast leadtime of at least 2 digits (e.g. `.GrbF06`, `.GrbF168`, etc.).
- We opened a [discussion](https://github.com/NOAA-EMC/UPP/discussions/1081) in the UPP repo to inquire about any straightforward way to predict the output filenames based on the input configuration.

Current plan of action:

- Implement the prefix-extraction method assuming the longer line blocks of the sort associated with the newer UPP version used by MPAS App.
- Generate suffixes based on what is currently observed from SRW and MPAS App, although we are aware this is probably not sufficiently general.
- Update the `uwtools` UPP driver to make the path to the `postxconfig-NT.txt` control file available under a required and schema-checked key, so that it can be consulted by the `output()` method.
- Implement `output()` as a function of `postxconfig-NT.txt` and the forecast leadtime, known to the driver.
